name: ci

on:
  push:
  schedule:
    # run this workflow every Monday at 1PM UTC
    - cron: "0 13 * * 1"

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:

  tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Cache Compiler Installations
      uses: actions/cache@v3
      with:
        path: |
          ~/.solcx
          ~/.vvm
        key: compiler-cache

    - name: Setup Node.js
      uses: actions/setup-node@v2.5.0

    - name: Install Ganache
      run: npm install -g ganache-cli@6.12.2

    - uses: pdm-project/setup-pdm@v2.5
      name: Setup PDM
      with:
        python-version: 3.9
        architecture: x64
        version: 1.7.2
        enable-pep582: true
    
    - name: Install dependencies
      run: pdm install
    
    - name: Run Tests
      run: pdm run brownie test -C
