name: deploy

on: [push]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  WEB3_INFURA_PROJECT_ID: ${{ secrets.WEB3_INFURA_PROJECT_ID }}
  PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}

jobs:

  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Cache Compiler Installations
      uses: actions/cache@v2
      with:
        path: |
          ~/.solcx
          ~/.vvm
        key: compiler-cache

    - name: Setup Node.js
      uses: actions/setup-node@v2.5.0

    - name: Install Ganache
      run: npm install -g ganache-cli@6.12.2

    - uses: pdm-project/setup-pdm@v2.5
      name: Setup PDM
      with:
        python-version: 3.9
        architecture: x64
        version: 1.7.2
        enable-pep582: true
    
    - name: Install dependencies
      run: pdm install
    
    - name: Deploy
      run: pdm run brownie run deploy --network kovan
